// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1GUBsyz9wF_75JJgkrKhR9FJJ42s33w8',
    appId: '1:709686857368:web:a8c71d2833896d4f600aed',
    messagingSenderId: '709686857368',
    projectId: 'proyecto-c3e1b',
    authDomain: 'proyecto-c3e1b.firebaseapp.com',
    storageBucket: 'proyecto-c3e1b.firebasestorage.app',
    measurementId: 'G-25T3D6RR6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AkAPebeyvQUFKW12juc1Jvnstsidyrc',
    appId: '1:709686857368:android:954742cfae1e7ead600aed',
    messagingSenderId: '709686857368',
    projectId: 'proyecto-c3e1b',
    storageBucket: 'proyecto-c3e1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlMyTiIqLeKxMSG2z1FxwMmOX_O7WPgtk',
    appId: '1:709686857368:ios:0841531756a2cd62600aed',
    messagingSenderId: '709686857368',
    projectId: 'proyecto-c3e1b',
    storageBucket: 'proyecto-c3e1b.firebasestorage.app',
    iosClientId:
        '709686857368-4ia8b1hsrj0c126tdakfjiktf2pr91rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.enriqueMasegosac1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlMyTiIqLeKxMSG2z1FxwMmOX_O7WPgtk',
    appId: '1:709686857368:ios:0841531756a2cd62600aed',
    messagingSenderId: '709686857368',
    projectId: 'proyecto-c3e1b',
    storageBucket: 'proyecto-c3e1b.firebasestorage.app',
    iosClientId:
        '709686857368-4ia8b1hsrj0c126tdakfjiktf2pr91rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.enriqueMasegosac1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1GUBsyz9wF_75JJgkrKhR9FJJ42s33w8',
    appId: '1:709686857368:web:bcf4f240dd608f7c600aed',
    messagingSenderId: '709686857368',
    projectId: 'proyecto-c3e1b',
    authDomain: 'proyecto-c3e1b.firebaseapp.com',
    storageBucket: 'proyecto-c3e1b.firebasestorage.app',
    measurementId: 'G-VV4JMG3KZT',
  );
}
